# Rustfmt configuration for XTrade project

# Use edition 2021 formatting
edition = "2021"

# Maximum line width
max_width = 100

# Formatting options
tab_spaces = 4
use_small_heuristics = "Default"
hard_tabs = false
newline_style = "Unix"

# Import formatting
reorder_imports = true

# Code formatting
fn_params_layout = "Tall"

# Other formatting options
force_explicit_abi = true
